export const siteConfig = {
  businessName: 'One Stop Outdoor Construction',
  ownerName: 'David Arabzadeh',
  phone: '(832) 945-8084',
  cleanPhone: '+18329458084',
  email: 'faridarabzadeh77@yahoo.com',
  domain: 'https://onestopoutdoorconstruction.net',
  primaryService: 'Patio Covers',
  services: [
    'Concrete & Driveways',
    'Outdoor Kitchens',
    'Pergolas',
    'Roofing Services',
    'Stamped Concrete',
    'Walkways & Pavers',
  ],
  rating: 5.0,
  reviewCount: 32,
  yearsInBusiness: 15,
  hours: '8am–5pm',
  slogan: 'Quality Outdoor Construction You Can Trust',
  serviceAreas: ['Richmond', 'Katy', 'Houston', 'Sugar Land', 'Rosenberg'],
  allServiceAreas: [
    'Richmond, TX', 'Katy, TX', 'Houston, TX', 'Sugar Land, TX',
    'Rosenberg, TX', 'Missouri City, TX', 'Fulshear, TX', 'Stafford, TX',
    'Pearland, TX', 'Cinco Ranch, TX', 'Greatwood, TX', 'Pecan Grove, TX',
  ],
  neighborhoods: 'Cinco Ranch, Greatwood, Pecan Grove, Telfair, Riverstone, Harvest Green, Sienna, New Territory, First Colony',
  zipCodes: ['77407', '77493', '77048', '77478', '77471'],
  testimonials: [
    // Best / most detailed reviews first
    { quote: "I can't rave about this company enough. From the initial visit and quote, there was no high pressure to proceed. Once my decision was made, work started promptly. Communication was excellent throughout the project. My additional requests were handled with ease, from increasing my concrete area to deciding to do stamped concrete. If you have any doubts about spending the additional money for stamped concrete, just do it — you will love it. David's crew was excellent, very personable, and kept me informed of the progress and what would be happening the next day. The transformation was completed in 8 working days, which I found amazing for replacing fascia and soffit, gutters, siding, extending the existing concrete, stamping it all, and of course the initial desire to have a covered patio. I would recommend these guys to anyone for any outdoor projects. This is one highly satisfied customer. It was so pleasant working with a company that actually cared about their customer and their satisfaction.", name: 'Barbara Autry Huyser', stars: 5 },
    { quote: "Amazing people! Outstanding team! We are so happy with the execution and delivery of our backyard project. We truly appreciate David and his team's commitment to our project. His efficient team finished the job earlier than expected and under budget. He quoted the best price of all the contractors and delivered excellent workmanship building our backyard. Awesome job One Stop Outdoor Construction, keep up the good work!", name: 'Vishakha Dastidar', stars: 5 },
    { quote: "One Stop Outdoor Construction Texas is one of the best contractors I have ever done business with. David was patient and came out to my house three times before we decided to proceed with construction. He listened to what we wanted and provided a quality patio at an affordable price. His team is very skilled and efficient and the best at what they do. I am extremely happy with my patio. David will be the first person I call if I am ever in need of any household repairs.", name: 'Angelina Smith', stars: 5 },
    { quote: "Thank you David and team for making our patio dream come true. We are completely satisfied with the end result. David addressed all of our needs and communicated with us throughout the entire process. His team does a great job — they are fast, organized, and good people. These pictures don't do it justice. Thank you!", name: 'Nathalie Correa', stars: 5 },
    { quote: "We are very happy with our covered patio and outdoor kitchen! David and his team did an amazing job. They were very efficient, flexible to accommodate all our requests and last minute changes, and they worked magic with the tiny space we had. We 100% recommend them.", name: 'Greilan Garcia Balmaseda', stars: 5 },
    { quote: "We had a vision for our patio and David and his crew built it into existence. David is very kind and understanding as well as easy to work with. His mission was to build it so it looked like it came with the house initially, and he exceeded expectations. We are extremely happy with our patio. I definitely recommend One Stop Outdoor Construction Texas as I have done so to family and friends.", name: 'AC Nguyen', stars: 5 },
    // Strong recommendations
    { quote: "Reasonable price and best of all, quality work. David is very receptive to the customer's plans and makes good recommendations to enhance the beautification of the project. Every crew member is pleasant and polite. They are very knowledgeable about what they do. We had a covered patio, with concrete floor, stamped concrete, and other work done. All completed within 5 days. Definitely satisfied with the outcome. 100% recommended.", name: 'Art DRjr', stars: 5 },
    { quote: "They did an excellent job. No job is perfect due to materials after a long while. Almost a year later I noticed some water leaking in my covered patio and let them know, and without hesitation they quickly repaired the problem. I highly recommend them for all types of construction. I'm a Filipino in a foreign country, but they treated me well as a customer without any boundaries.", name: 'ArNor MoSu', stars: 5 },
    { quote: "David did our patio in April this year and we love it! He was extremely professional and reasonably priced. Unlike most contractors we have worked with in the past, he was always there when he said he would be and ensured we were happy with the results. Would definitely use this company again and again and recommend them to all our neighbors.", name: 'Jennifer Clark', stars: 5 },
    { quote: "This guy David is real, with no-fuss pricing and an eye for refinement and detail. He works with you to provide the best options for your budget. Takes care of HOA approvals. Timely execution and proper post-construction cleanup. Highly recommended.", name: 'Yogesh Varma', stars: 5 },
    { quote: "We are so happy with our covered patio. David was amazing to work with. It took a little longer than planned due to city permits, but once approved, David and his team worked fast and efficiently. I would recommend 100%.", name: 'Brandi Kraemer Tanksley', stars: 5 },
    { quote: "David and his team did an amazing job on my patio. They went above and beyond what my wife and I expected. One Stop Construction gave us an estimated timeline and had the job complete on schedule. Thank you guys for making this a pleasant experience. We're very happy with our custom patio.", name: 'Corinthians Greenburg III', stars: 5 },
    // Solid positive reviews
    { quote: "David was recommended by my friend and so I hired them. I was surprised my patio was finished within 3 days without cutting corners. David and his crew were very professional and efficient. They did an awesome job and I love my patio. Highly recommend this company!", name: 'Lea Alcoseba', stars: 5 },
    { quote: "We were incredibly impressed by every aspect of working with One Stop Outdoor Construction. Everyone is so impressed with their work! I have recommended them to so many friends. If you are thinking about getting some upgrades, give them a call!", name: 'Rob Hofschulte', stars: 5 },
    { quote: "David and his team were extremely professional. They definitely matched the paint and roof shingles with my current patio. David and one of his guys stayed late to make sure the concrete was completed and dry. Love my patio! Thank you for such a good job!", name: 'Verenice De Leon', stars: 5 },
    { quote: "These guys are as professional as they come. They do fantastic work and in a timely manner. I will be using them again when we do our patio cover. A little disclaimer — don't judge them on the fire pit, that's my doing haha.", name: 'James Wiley', stars: 5 },
    { quote: "The absolute best at outdoor living! David and his team got the job done! Great customer service and great recommendations! Beautiful results.", name: 'Ashley Rogers Williams', stars: 5 },
    { quote: "Love One Stop. They are honest and will work with your budget. They are helping me build my dream backyard. Everything they have done has been high quality work. Love, love, love them.", name: 'Adrianna Poteste', stars: 5 },
    { quote: "Great job David and team. We love our new outdoor living space. Every team member was polite, hard working, and respectful. Thank you! Happy to offer any reference needed.", name: 'Matthew Vesely', stars: 5 },
    { quote: "David is excellent to work with and his team are incredibly efficient and professional. We are very happy with the final product and would highly recommend their service to anyone!", name: 'Asher Rudolph', stars: 5 },
    { quote: "Very professional! All the guys were super nice and answered my millions of questions as the project went along. They were available when I needed to talk to them and went above and beyond for me.", name: 'Christen Staton', stars: 5 },
    { quote: "David and his crew replaced our roof a couple of years ago and did a really wonderful job. Our next door neighbor hired him to replace her roof too. Awesome service.", name: 'Ruby Pretila Reese', stars: 5 },
    { quote: "David and his team did an outstanding job. I recommend y'all use them for the services that they're offering. Thanks again David to you and your team — job well done.", name: 'Mechie Demetria Reed', stars: 5 },
    { quote: "David and his crew are some of the best people I have ever done business with. My wife and I are really happy with the backyard patio they built for us. Hope to do business with you again, David.", name: 'Juan Cantu', stars: 5 },
    { quote: "David and his team did a great job on our patio addition and the concrete stamping is a great addition. We are very pleased.", name: 'Michael Cantrell', stars: 5 },
    // Shorter positive reviews
    { quote: "Excellent patio and concrete company. They are a very professional team, well managed, and can deliver your project on time!", name: 'Ysabel Pacheco Millan', stars: 5 },
    { quote: "Very proficient and reasonably priced company. Thank you David and the whole group. I recommend this whole group 100%.", name: 'Cel Bustamante', stars: 5 },
    { quote: "Did a great job on my covered patio. Very excited to finally have an outdoor space. Looking forward to enjoying it with friends this summer!", name: 'Ann Siverson', stars: 5 },
    { quote: "We got a wonderful patio designed and built by One Stop Outdoor Construction last December in our home in Katy. Highly recommend this company.", name: 'Istvan Kathi', stars: 5 },
  ],
  faqs: [
    { q: 'How much does a free estimate cost?', a: 'Nothing — every estimate from One Stop Outdoor Construction is 100% free with no strings attached. We come out, look at the job, and give you an honest, competitive price on the spot. No pressure, no obligation.' },
    { q: 'What areas do you serve?', a: 'We proudly serve Richmond (77407), Katy (77493), Houston (77048), Sugar Land, Rosenberg, and surrounding communities including Missouri City, Fulshear, Stafford, Cinco Ranch, Greatwood, and Pecan Grove.' },
    { q: 'Is One Stop Outdoor Construction licensed and insured?', a: 'Yes. We are a fully licensed general contractor and carry comprehensive liability insurance on every job. Your property and our crew are always covered.' },
    { q: 'How fast can you start a project?', a: 'We pride ourselves on fast response and quick scheduling. Most projects can be started within 1-2 weeks of approval. Contact us and we will get you on the calendar as quickly as possible.' },
    { q: 'What is your most popular service?', a: 'Patio covers are our #1 service. We install traditional lattice, solid insulated laminated, and aluminum patio covers with optional skylight systems and ceiling fans — all fully customizable to your preferences.' },
    { q: 'Do you do custom outdoor kitchen builds?', a: 'Absolutely. We specialize in designing and building custom outdoor kitchens tailored to your style, needs, and budget. From grills and countertops to full outdoor living spaces.' },
    { q: 'What types of concrete work do you offer?', a: 'We offer a full range of concrete services including traditional driveways, stamped concrete, colored concrete, decorative concrete, pavers, walkways, patios, retaining walls, and more. Over 15 years of experience in concrete applications.' },
  ],
};

export interface ServiceItem {
  slug: string;
  title: string;
  media: { type: 'image' | 'video'; src: string }[];
  summary: string;
  details: string[];
  turnaround: string;
  longDescription: string;
  keywords: string[];
}

export const serviceData: ServiceItem[] = [
  {
    slug: 'patio-covers',
    title: 'Patio Covers',
    media: [
      { type: 'video', src: '/service/IMG_2790.mp4' },
      { type: 'video', src: '/service/IMG_5260.mp4' },
      { type: 'video', src: '/service/IMG_5592.mp4' },
      { type: 'video', src: '/service/IMG_6538.mp4' },
      { type: 'video', src: '/service/IMG_6548.mp4' },
      { type: 'image', src: '/OneStopOutdoor_Photos/photo_04.jpg' },
      { type: 'image', src: '/OneStopOutdoor_Photos/photo_05.jpg' },
      { type: 'image', src: '/OneStopOutdoor_Photos/photo_07.jpg' },
      { type: 'image', src: '/OneStopOutdoor_Photos/photo_08.jpg' },
      { type: 'image', src: '/OneStopOutdoor_Photos/photo_17.jpg' },
      { type: 'image', src: '/service/IMG_4896.jpg' },
    ],
    summary: 'Transform your outdoor space with a custom patio cover — lattice, solid insulated, or aluminum with optional skylights and ceiling fans.',
    details: [
      'Traditional open-style lattice patio covers',
      'Solid insulated laminated patio covers',
      'Aluminum patio covers with optional skylights',
      'Ceiling fan installation and custom color matching',
    ],
    turnaround: 'Most projects completed in 1–2 weeks',
    longDescription: 'Among our many services, patio covers are our specialty. We install any style including traditional open-style lattice patio covers, solid insulated laminated patio covers, and aluminum patio covers. Our patio covers feature optional Skylight Systems and ceiling fans and are fully customizable to fit your material and color preferences. A covered patio not only enhances your outdoor living experience but also increases your home value.',
    keywords: ['patio cover Richmond TX', 'patio cover Katy TX', 'covered patio Houston TX', 'patio cover installation Sugar Land'],
  },
  {
    slug: 'concrete-driveways',
    title: 'Concrete & Driveways',
    media: [
      { type: 'video', src: '/service/IMG_6542.mp4' },
      { type: 'image', src: '/OneStopOutdoor_Photos/photo_06.jpg' },
      { type: 'image', src: '/OneStopOutdoor_Photos/photo_18.jpg' },
      { type: 'image', src: '/OneStopOutdoor_Photos/photo_19.jpg' },
      { type: 'image', src: '/OneStopOutdoor_Photos/photo_24.jpg' },
      { type: 'image', src: '/OneStopOutdoor_Photos/photo_27.jpg' },
    ],
    summary: 'Top-notch decorative concrete and driveway installations by certified, experienced professionals — personalized to your preferences.',
    details: [
      'Stamped and colored concrete applications',
      'Driveway installation and replacement',
      'Decorative concrete for patios, pool decks, and walkways',
      'Over 15 years of concrete expertise',
    ],
    turnaround: 'Completed in 3–7 days depending on scope',
    longDescription: 'With over 15 years of experience, we offer custom concrete and decorative concrete applications through integral colored concrete and stamped concrete to add design and color to exterior surfaces such as driveways, swimming pools, patios, and walkways. Every project we complete is personalized to the preferences of our clients, installed by certified, experienced professionals.',
    keywords: ['concrete contractor Richmond TX', 'driveway installation Katy TX', 'stamped concrete Houston TX', 'decorative concrete Sugar Land'],
  },
  {
    slug: 'outdoor-kitchens',
    title: 'Outdoor Kitchens',
    media: [
      { type: 'video', src: '/service/7954120423b34f3fa5e5b918940baa56.mp4' },
      { type: 'video', src: '/service/IMG_3984.mp4' },
      { type: 'video', src: '/service/IMG_4125.mp4' },
      { type: 'video', src: '/service/IMG_4907.mp4' },
      { type: 'video', src: '/service/a3b9eb000bfe4c33adf03425f38b804d.mp4' },
      { type: 'video', src: '/service/dc003ed213f245a29f0dfff749d23e1c.mp4' },
      { type: 'image', src: '/OneStopOutdoor_Photos/photo_10.jpg' },
      { type: 'image', src: '/OneStopOutdoor_Photos/photo_21.jpg' },
      { type: 'image', src: '/OneStopOutdoor_Photos/photo_22.jpg' },
      { type: 'image', src: '/OneStopOutdoor_Photos/photo_28.jpg' },
      { type: 'image', src: '/OneStopOutdoor_Photos/photo_29.jpg' },
      { type: 'image', src: '/service/IMG_4795.jpg' },
    ],
    summary: 'Custom-designed outdoor kitchens built to your style, needs, and budget — with endless possibilities for your perfect outdoor cooking space.',
    details: [
      'Custom design and build from concept to completion',
      'Built-in grills, countertops, and stone veneer',
      'Plumbing and electrical integration',
      'Premium materials and finishes',
    ],
    turnaround: 'Typically 2–4 weeks',
    longDescription: 'We specialize in designing and building custom, high-quality outdoor kitchens. Our approach lets you see what options are available and the endless possibilities that can be achieved to truly give you a one-of-a-kind outdoor space that is unique to your style, needs, and budget. From built-in grills to full outdoor bars, we handle it all.',
    keywords: ['outdoor kitchen Richmond TX', 'outdoor kitchen builder Katy TX', 'custom outdoor kitchen Houston TX', 'outdoor kitchen installation Sugar Land'],
  },
  {
    slug: 'pergolas',
    title: 'Pergolas',
    media: [
      { type: 'image', src: '/service/IMG_6339.jpeg' },
      { type: 'image', src: '/OneStopOutdoor_Photos/photo_12.jpg' },
      { type: 'image', src: '/OneStopOutdoor_Photos/photo_14.jpg' },
      { type: 'image', src: '/OneStopOutdoor_Photos/photo_15.jpg' },
      { type: 'image', src: '/OneStopOutdoor_Photos/photo_16.jpg' },
    ],
    summary: 'Beautiful pergolas that provide the ideal space for relaxing, entertaining, and enjoying outdoor living year-round.',
    details: [
      'Custom wood and metal pergola designs',
      'Attached or freestanding structures',
      'Optional string lighting and fan installations',
      'Increases home value and curb appeal',
    ],
    turnaround: 'Most installations in 3–5 days',
    longDescription: 'Pergolas provide the ideal space for relaxing, entertaining, and enjoying the Houston area\'s great climate. In addition to providing an outdoor living space, pergolas help increase a home\'s value, add to its overall beauty, and protect residents from the elements. We build custom pergolas in wood, metal, and composite materials to match any architectural style.',
    keywords: ['pergola builder Richmond TX', 'custom pergola Katy TX', 'pergola installation Houston TX', 'pergola contractor Sugar Land'],
  },
  {
    slug: 'roofing',
    title: 'Roofing Services',
    media: [
      { type: 'image', src: '/onestop/images/service_roofing.png' },
    ],
    summary: 'A wide variety of residential roofing from green roofing to metal and shingle — selecting the right material for a long-lasting roof.',
    details: [
      'Shingle, metal, and flat roofing installations',
      'Green roofing and bitumen (cold or torch applied)',
      'Roof repair and replacement',
      'Material selection guidance for longevity',
    ],
    turnaround: 'Most roofs completed in 1–3 days',
    longDescription: 'We offer a wide variety of residential roofing types from green roofing installations to bitumen cold or torch applied, metal and shingle roofs. Selecting the right roofing material is always the key to a long-lasting, happy roof. Our experienced team will guide you through the best options for your home and budget.',
    keywords: ['roofing contractor Richmond TX', 'roof replacement Katy TX', 'roofing services Houston TX', 'roof installation Sugar Land'],
  },
  {
    slug: 'walkways-pavers',
    title: 'Walkways & Pavers',
    media: [
      { type: 'image', src: '/facebook/walkway.jpg' },
    ],
    summary: 'Paver stone walkways that add beauty, curb appeal, strength, and flexibility to your property.',
    details: [
      'Paver stone walkway design and installation',
      'Flagstone, slate, and natural stone options',
      'Retaining walls and landscape borders',
      'Durable, low-maintenance finishes',
    ],
    turnaround: 'Most walkways completed in 2–4 days',
    longDescription: 'The beauty and curb appeal that a paver stone walkway will add to your home is only exceeded by its strength and flexibility. A professionally installed paver walkway or pathway around your property may be just what you need to ensure you never walk in the mud or worry about tripping over uneven or broken concrete pathways again.',
    keywords: ['walkway installation Richmond TX', 'paver contractor Katy TX', 'stone walkway Houston TX', 'paver installation Sugar Land'],
  },
];

export const navLinks = [
  { label: 'Home', href: '/' },
  { label: 'Services', href: '/services' },
  { label: 'About', href: '/about' },
  { label: 'Gallery', href: '/gallery' },
  { label: 'Reviews', href: '/#reviews' },
  { label: 'Blog', href: '/blog' },
  { label: 'Contact', href: '/contact' },
];
